# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Welcome.create(
  title: "PIAE",
  subtitle: "Plataforma de Integración Y Asocio Empresarial",
  about: "CDMYPE-UGB es parte de la alianza público-privada-academia que el Gobierno de la República, a través de CONAMYPE que tiene con universidades y entidades del sector privado. Los centros ofrecen servicios de asesoría, capacitación y asistencia técnica a las y los empresarios que los soliciten",
  address: "CDMYPE UGB, Santa Maria, Usulutan",
  email: "cdmypeugb@gmail.com",
  phone: 26321527,
  vision: "Ser reconocidos a nivel nacional como una institusión generadora de cultura emprendedora y empresarial, mediante procesos transparentes, equitativos y de calidad, que busquen crear impacto economico y liderazgo de la MYPE, fomentando su autosostenibilidad.",
  mission: "Somos un centro de desarrollo, que brinda servicios integrales empresariales mediante el acompañamiento a la MYPE contribuyendo asi a la generacion de impacto economico"
)

Service.create!([
  {
    name: "Asesoria empresarial",
    description: "Se brinda acompañamiento integral a la persona emprendedora o empresaria para ayudarle a resolver problemas en áreas de la empresa como: Administración, producción, mercadeo, finanzas, etc.",
    image: "negocios.jpg",
  },
  {
    name: "Asesoria en el uso de las TIC's",
    description: "Los empresarios y empresarias reciben apoyo para aplicar la tecnología (informática, sistemas computacionales, dispositivos electrónicos, internet, telecomunicaciones, etc) y con ello acceder a nuevos servicios e más información, mejorar sus competencias, abrirse a nuevos mercados, entre otros.",
    image: "tic.jpg",
  },
  {
    name: "Empresarialidad femenina",
    description: "Es un proceso de acompañamiento especializado a la emprendedora o empresaria de la MYPE de subsistencia, cuenta propia, individual o asociada.",
    image: "woman.jpg",
  },
  {
    name: "Asesoria financiera",
    description: "Proceso de acompañamiento que se hace a un cliente por un periodo para desarrollar las condiciones necesarias para optar a un financiamiento para su empresa.",
    image: "money.jpg",
  },
  {
    name: "Asistencia tecnica",
    description: "Se ofrecen servicios técnicos en temas de gestión empresarial o temas especializados, fortaleciendo aspectos como: diseños de procesos productivos, reformulación y diversificación de productos, imagen comercial, planes de mercadeo, diseño de estrategia de promoción o publicitaria u otros que requiera la empresa",
    image: "nota.jpg",
  },
  {
    name: "Capacitaciones",
    description: "Se brinda información en diferentes áreas, de manera grupal para una o varias empresas en diversos temas como: características empresariales personales, planes de negocios, técnicas efectivas de ventas, servicio al cliente, etc.",
    image: "conferencia.jpg",
  }
])

Municipality.create!([
  { title: "Alegria" },
  { title: "Berlin" },
  { title: "California" },
  { title: "Concepcion Batres" },
  { title: "El Triunfo" },
  { title: "Ereguayquín" },
  { title: "Estanzuelas" },
  { title: "Jiquilisco" },
  { title: "Jucuapa" },
  { title: "Jucuaran" },
  { title: "Mercedes Umaña" },
  { title: "Nueva Granada" },
  { title: "Ozatlan" },
  { title: "Puerto El Triunfo" },
  { title: "San Agustin" },
  { title: "San Buenaventura" },
  { title: "San Dionisio" },
  { title: "San Francisco Javier" },
  { title: "Santa Elena" },
  { title: "Santa Maria" },
  { title: "Santiago de Maria" },
  { title: "Tecapán" },
  { title: "Usulutan" },
  { title: "Otro" }
])

Entry.create!([
  { title: "Alimentos", image: "alimentos.jpg" },
  { title: "Apicultura", image: "apicultura.jpg" },
  { title: "Cafeteria", image: "cafeteria.jpg" },
  { title: "Carniceria", image: "carniceria.jpg" },
  { title: "Constructora & Ferreteria", image: "constructura.jpg" },
  { title: "Diseño grafico", image: "diseñador.jpg" },
  { title: "Agricultura", image: "agricultura.jpg" },
  { title: "Hosteleria y Turismo", image: "hoteles.jpg" },
  { title: "Informatica", image: "informatica.jpg" },
  { title: "Lacteos", image: "lacteos.jpg" },
  { title: "Restaurante", image: "restaurante.jpg" },
  { title: "Sala de belleza", image: "cosmetologia.jpg" },
  { title: "Panaderia", image: "panaderia.jpg" }
])


Enterprise.create!([
  {
    title: "Cafe Don Diego",
    email: "cafedondiego@gmail.com",
    municipality_id: 9,
    entry_id: 3,
    owner: "Willian Sabino Alvarado",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "San Martin de Sonia",
    email: "sanmartinsonia@gmail.com",
    municipality_id: 23,
    entry_id: 11,
    owner: "Sonia Elizabeth Batres",
    about: "",
    phone: 1234,
    image: "san_martin_sonia.jpg",
    address: "",
  },
  {
    title: "La esquina de olocuilta",
    email: "laesquinadeolocuilta@gmail.com",
    municipality_id: 8,
    entry_id: 11,
    owner: "Carolina Vladimir Portillo",
    about: "",
    phone: 1234,
    image: "la_esquina_olocuilta.jpg",
    address: "",
  },
  {
    title: "Rinconcito Familiar",
    email: "rinconcitofamiliar@gmail.com",
    municipality_id: 1,
    entry_id: 11,
    owner: "Delfina de Jesus Rodriguez",
    about: "",
    phone: 1234,
    image: "rinconcito_familiar.jpg",
    address: "",
  },
  {
    title: "Pasteleria Trigo Puro",
    email: "pasteleriatrigopuro@gmail.com",
    municipality_id: 23,
    entry_id: 13,
    owner: "Jaime Antonio Blandon",
    about: "",
    phone: 1234,
    image: "pasteleria_trigo_puro.jpg",
    address: "",
  },
  {
    title: "Carpinteria Ramirez",
    email: "carpinteriaramirez@gmail.com",
    municipality_id: 4,
    entry_id: 5,
    owner: "Mayra Patricia Ramirez",
    about: "",
    phone: 1234,
    image: "carpinteria_ramirez.jpg",
    address: "",
  },
  {
    title: "Comedor La Bendicion",
    email: "comedorlabendicion@gmail.com",
    municipality_id: 13,
    entry_id: 11,
    owner: "Esmeralda Calix Orellana",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Electri Ivan",
    email: "electriivan@gmail.com",
    municipality_id: 20,
    entry_id: 5,
    owner: "Elfidio Elenilson Tevez",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Restaurante La Joya",
    email: "restaurantelajoya@gmail.com",
    municipality_id: 5,
    entry_id: 11,
    owner: "Maria de la Cruz Orellana",
    about: "",
    phone: 1234,
    image: "restaurante_la_joya.jpg",
    address: "",
  },
  {
    title: "Tierramar Restaurante",
    email: "tierramarrestaurante@gmail.com",
    municipality_id: 23,
    entry_id: 11,
    owner: "Carmen Alicia Gonzalez",
    about: "",
    phone: 1234,
    image: "restaurante_tierramar.jpg",
    address: "",
  },
  {
    title: "Banquetes Mi querido Jiquilisco",
    email: "miqueridojiquilisco@gmail.com",
    municipality_id: 8,
    entry_id: 11,
    owner: "Teresa Magali Navarro",
    about: "",
    phone: 1234,
    image: "mi_querido_jiquilisco.jpg",
    address: "",
  },
  {
    title: "Constructora & Ferreteria Granadeño",
    email: "ferreteriagranadeno@gmail.com",
    municipality_id: 5,
    entry_id: 5,
    owner: "David Romero",
    about: "",
    phone: 1234,
    image: "ferreteria_granadeno.jpeg",
    address: "",
  },
  {
    title: "Comedor El Progreso",
    email: "comedorelprogreso@gmail.com",
    municipality_id: 5,
    entry_id: 11,
    owner: "Yulme Senaida Canizales",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "La casa del arbol",
    email: "lacasadelarbol@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Ruben Ernesto Jovel",
    about: "",
    phone: 1234,
    image: "la_casa_del_arbol.png",
    address: "",
  },
  {
    title: "Distribuidora Castillo",
    email: "distribuidoracastillo@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Erick Daniel Castillo",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Asociacion cooperativa de producción pesquera de Puerto Parada de R.L",
    email: "asociacionpesquera@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Estudio Digital La Ceiba",
    email: "estudiodigitallaceiba@gmail.com",
    municipality_id: 11,
    entry_id: 1,
    owner: "Oscar Alexander Bermudez",
    about: "",
    phone: 1234,
    image: "la_ceiba.jpg",
    address: "",
  },
  {
    title: "Panaderia Beckys",
    email: "panaderiabeckys@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Edwin Alexander Morales",
    about: "",
    phone: 1234,
    image: "panaderia_beckys.jpg",
    address: "",
  },
  {
    title: "Coffee Book Heaven",
    email: "coffeebookheaven@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    about: "",
    phone: 1234,
    image: "coffee_book_heaven.jpg",
    address: "",
  },
  {
    title: "Laptop Tech",
    email: "laptopteach@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Juan Jose Campos",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "The coffee shop",
    email: "thecoffeeshop@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Rosalva Santin Diaz",
    about: "",
    phone: 1234,
    image: "the_coffee_shop.jpg",
    address: "",
  },
  {
    title: "Comite de desarrollo turistico de California",
    email: "comiteturisticocalifornia@gmail.com",
    municipality_id: 3,
    entry_id: 1,
    owner: "Gustavo Adolfo Funes",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Productos Naturales",
    email: "productosnaturales@gmail.com",
    municipality_id: 8,
    entry_id: 1,
    owner: "Carlos Ernesto Flores",
    about: "",
    phone: 1234,
    image: "de_vida.jpg",
    address: "",
  },
  {
    title: "Constructora & Ferreteria del Rio",
    email: "ferreteriadelrio@gmail.com",
    municipality_id: 8,
    entry_id: 1,
    owner: "Carlos Manuel Romero",
    about: "",
    phone: 1234,
    image: "ferreteria_del_rio.jpg",
    address: "",
  },
  {
    title: "Carniceria Asarela",
    email: "carniceriaasarela@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Ana Maria Chicas",
    about: "",
    phone: 1234,
    image: "asarela.jpg",
    address: "",
  },
  {
    title: "Grupo San Jose La Coquera",
    email: "gruposanjose@gmail.com",
    municipality_id: 4,
    entry_id: 1,
    owner: "Pedro Geovany Chavarria",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "M.Design + Arte",
    email: "mdesignarte@gmail.com",
    municipality_id: 7,
    entry_id: 1,
    owner: "Mario Ernesto Hernandez",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Country Club La Pirraya",
    email: "clublapirraya@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Delmy Adriana Aviles",
    about: "",
    phone: 1234,
    image: "country_club_la_pirraya.jpg",
    address: "",
  },
  {
    title: "La Karreta de Alberto",
    email: "lacarretadealberto@gmail.com",
    municipality_id: 21,
    entry_id: 1,
    owner: "Jose Alberto Argueta",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Imprenta Cerna",
    email: "imprentacerna@gmail.com",
    municipality_id: 21,
    entry_id: 1,
    owner: "Maria Lourdes Cerna",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Productos del campo",
    email: "productosdelcampo@gmail.com",
    municipality_id: 24,
    entry_id: 1,
    owner: "Jose Antonio Guandique",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Neto Sport",
    email: "netosport@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Fernando Ernesto Maravilla",
    about: "",
    phone: 1234,
    image: "neto_sport.jpg",
    address: "",
  },
  {
    title: "El Molcajete",
    email: "elmolcajete@gmail.com",
    municipality_id: 1,
    entry_id: 1,
    owner: "Erick Omar Estrada",
    about: "",
    phone: 1234,
    image: "el_molcajete.jpg",
    address: "",
  },
  {
    title: "Cafe de mi tierra",
    email: "cafedemitierra@gmail.com",
    municipality_id: 11,
    entry_id: 1,
    owner: "Oswaldo Antonio Galan",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Avicola El Progreso",
    email: "avicolaelprogreso@gmail.com",
    municipality_id: 7,
    entry_id: 1,
    owner: "Adelina Alfaro de Mejia",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Granja El Escarbadero",
    email: "granjaelescarbadero@gmail.com",
    municipality_id: 7,
    entry_id: 1,
    owner: "Erika Yamileth Aviles",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Carpinteria 2000",
    email: "carpinteria2000@gmail.com",
    municipality_id: 7,
    entry_id: 1,
    owner: "Salomon Cruz",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Hotel & Restaurante La Pirraya",
    email: "hotellapirraya@gmail.com",
    municipality_id: 6,
    entry_id: 1,
    owner: "Delmy del Carmen Sanchez",
    about: "",
    phone: 1234,
    image: "",
    address: "",
  },
  {
    title: "Ana Salon",
    email: "anasalon@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Ana María Quiroz Rivera",
    about: "",
    phone: 26135970,
    image: "ana_salon.jpg",
    address: "",
  },
  {
    title: "Claricia Escuela Tenica de Cosmestologia",
    email: "claricia@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Claricia Lisbeth Campos Reyes",
    about: "",
    phone: 77451296,
    image: "Claricia_escuela.jpg",
    address: "",
  },
  {
    title: "Torito Ranch",
    email: "toritoranch@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: ".",
    about: "",
    phone: 62008053,
    image: "Torito_Ranch.jpg",
    address: "Usulután, Usulután",
  },
  {
    title: "Dulcería Duran",
    email: "dulceriaduran@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Fátima María Durán Alvarenga",
    about: "",
    phone: 79164306,
    image: "DULCERIA_DURAN.png",
    address: "Usulután, Usulután",
  },
  {
    title: "Comedor Mary",
    email: "comedormary@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "María Felicita Sanchez de Carpio",
    about: "",
    phone: 75833014,
    image: "Comedor_Mary.png",
    address: "Usulután, Usulután",
  },
  {
    title: "Asociación Cooperativa de de Producción Agropecuaria Aguas Termales de R.L",
    email: "aguastermales@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "José Saturino Alvarado Paredes",
    about: "",
    phone: 77022528,
    image: "AGUAS_TERMALES.png",
    address: "Concepción Batres, Usulután",
  },
  {
    title: "Asociación Cooperativa de Comercialización, Aprovisionamiento y Producción Agropecuaria la Tres Ceibas Unidad de R.L",
    email: "lastresceibas@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Roberto Arturo Rivera Castro",
    about: "",
    phone: 61592399,
    image: "LAS_3_CEIBAS.png",
    address: "Concepción Batres, Usulután",
  },
  {
    title: "Comedor y Antojitos Bessy",
    email: "antojitosbessy@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Vilma Rosaura Saravia de Rodriguez",
    about: "",
    phone: 77827862,
    image: "Comedor_Antojitos_Bessy.png",
    address: "Concepción Batres, Usulután",
  },
  {
    title: "Modas Daniela",
    email: "modasdaniela@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Ruth Mabel Navarrete de Granados",
    about: "",
    phone: 77401658,
    image: "Modas_Daniela.png",
    address: "Jucuapa, Usulután",
  },
  {
    title: "Modas Monica",
    email: "modasmonica@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Monica Dabeiva Navarrete Alvarado",
    about: "",
    phone: 79525140,
    image: "Modas_Monica.png",
    address: "Jucuapa, Usulután",
  },
  {
    title: "Impacto Digital",
    email: "impactodigital@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Jorge Emanuel Mejía Molina",
    about: "",
    phone: 72419889,
    image: "Impacto_Digital.jpg",
    address: "Santiago de María, Usulután",
  },
  {
    title: "Lumont Salon y Spa",
    email: "lumontsalonyspa@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "María Lucresia Monterrosa de Henriqueza",
    about: "",
    phone: 7026-3532,
    image: "Lumont_Salon_Spa.png",
    address: "Usulután, Usulután",
  },
  {
    title: "Triunfolac",
    email: "triunfolac@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Abraham Orlando Turcios Castillo",
    about: "",
    phone: 78894876,
    image: "Triunfolac.jpg",
    address: "Santiago de María, Usulután",
  },
  {
    title: "Mely´s Nails",
    email: "melysnails@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Jacqueline Melissa Ramírez Castellón",
    about: "",
    phone: 72872314,
    image: "Melys_nails.png",
    address: "El Triunfo, Usulután",
  },
  {
    title: "Panaderia Cecy",
    email: "panaderiacecy@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Ana Cecilia Catro Dominguez",
    about: "",
    phone: 74787977,
    image: "panaderia_cecy.png",
    address: "Colonia los Naranjos, Usulután",
  },
  {
    title: "Asociación de Personas Productoras y Emprendedoras con Visión al Futuro",
    email: "visionalfuturo@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Jose Guillermo Guerreo Vasquez",
    about: "",
    phone: 79953554,
    image: "APVF.png",
    address: "Concepción Batres, Usulután",
  },
  {
    title: "Confecciones Ramos y Gutierrez",
    email: "ramosygutierrez@gmail.com",
    municipality_id: 23,
    entry_id: 1,
    owner: "Lisardo de Jesús Gutierrez Ávalos",
    about: "",
    phone: 79647146,
    image: "ConfeccionesRamosGutierrez.png",
    address: "Santa Elena, Usulután",
  }
])

JobCategory.create!([
  { title: "Agricultor", image: "agricultor.jpg" },
  { title: "Apicultor", image: "apicultor.jpg" },
  { title: "Cocinero/a", image: "cocinero.jpg" },
  { title: "Carpintero", image: "carpintero.jpg" },
  { title: "Contador", image: "contador.jpg" },
  { title: "Electricista", image: "electrician.png" },
  { title: "Enfermera", image: "nurse.png" },
  { title: "Fontanero", image: "plumber.png" },
  { title: "Gerente", image: "gerente.jpg" },
  { title: "Informatico/a", image: "informatico.jpg" },
  { title: "Mesero/a", image: "waiter.png" },
  { title: "Motorista", image: "taxi-driver.png" },
  { title: "Panadero", image: "panadero.jpg" },
  { title: "Programador", image: "informatico.jpg" },
  { title: "Secretaria", image: "secretaria.jpg" },
  { title: "Cosmetologa/o", image: "" }
])

Story.create([
  {
    title: "Decoraciones artisticas Ashley",
    description: "Decoraciones artisticas Ashley",
    video: "vilma.mp4",
    image: "ashley.png"
  },
  {
    title: "Panaderia La Espiga",
    description: "Panaderia La Espiga",
    video: "la_espiga.mp4",
    image: "espiga.png"
  },
  {
    title: "Comida Mexicana Litos",
    description: "Decoraciones artisticas Ashley",
    video: "litos.mp4",
    image: "litos.png"
  },
  {
    title: "Modas Lucy",
    description: "Modas lucy",
    video: "lucy.mp4",
    image: "lucy.png"
  },
  {
    title: "Mi pueblito",
    description: "Decoraciones artisticas Ashley",
    video: "mipueblito.mp4",
    image: "mipueblito.png"
  },
  {
    title: "Julio Nain Perdomo",
    description: "Julio Nain Perdomo",
    video: "nain.mp4",
    image: "nain.png"
  },
  {
    title: "Cafe el nucleo",
    description: "Cafe el nucleo",
    video: "mojaras.mp4",
    image: "mojaras.png"
  }
])

Adviser.create!([
  {
    name: "Ana",
    surname: "Castellon",
    description: "Licenciada en Administración de empresas de la Universidad Gerardo Barrios, Maestría en Dirección Estratégica de Empresas de la Universidad Gerardo Barrios",
    position: "Asesora empresarial",
    image: "ana_castellon.jpg",
    email: "ana@gmail.com",
    password: "12345678"
  },
  {
    name: "Merlyn",
    surname: "de Arias",
    description: "Licenciada en Administración de Empresas y Máster en Dirección Estratégica de Empresa, con amplia experiencia en asesorías empresariales al sector MYPE del Departamento de Usulután y certificada como Asesor de Negocios de SBDCGlobal. Proactiva, disciplinada, comprometida y constantes con los resultados de cambio de los empresarios/as.",
    position: "Asesora empresarial",
    image: "merlyn_arias.jpg",
    email: "merlyn@gmail.com",
    password: "12345678"
  },
  {
    name: "Santiago",
    surname: "Navarrete",
    description: "Ingeniero en Sistemas y Redes Informáticas, Graduado de la Universidad Gerardo Barrios, San Miguel. Preespecializado en SEGURIDAD EN SERVIDORES Y REDES INALÁMBRICAS.",
    position: "Asesor empresarial",
    image: "santiago_navarrete.jpg",
    email: "santiago@gmail.com",
    password: "12345678"
  },
  {
    name: "Roxana",
    surname: "León",
    description: "",
    position: "Asesora empresarial",
    image: "roxana_leon.jpg",
    email: "roxana@gmail.com",
    password: "12345678"
  },
])
